apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - strimzi-topic-operator-0.13.0.yaml

commonAnnotations:
  sidecar.istio.io/inject: "false"

patchesStrategicMerge:
  - patch-deployment.yaml
